export const AUTO_LOGIN = 'AUTO_LOGIN';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const FETCH_DEPARTMENTS = 'FETCH_DEPARTMENTS';

export const CREATE_DEPARTMENT = 'CREATE_DEPARTMENT';
export const UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT';
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT';

export default AUTO_LOGIN;
