export const AUTO_LOGIN = 'AUTO_LOGIN';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const FETCH_DEPARTMENTS = 'FETCH_DEPARTMENTS';

export const CREATE_DEPARTMENT = 'CREATE_DEPARTMENT';
export const UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT';
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT';

export const FETCH_AREAS = 'FETCH_AREAS';

export const FETCH_ADDRESS = 'FETCH_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const CREATE_ADDRESS = 'CREATE_ADDRESS';

export default AUTO_LOGIN;
